In [1]:
import pandas as pd

import scripts.py.advanced
from py.advanced import solve_advanced

In this example we will use TF activity scores for selected TF.
As a target, we use PD-L1 expression.
We first load this data.

In [2]:
X_TFactivities_broad = pd.read_csv("data/X_TFactivities_Broad.csv")
y_PDL1expression_broad = pd.read_csv("data/Y_PDL1expression_Broad.csv")

For the input data X, we need rows to correspond to samples and columns to correspond to TF.
The sample ID should be the index. We do this as follows:

In [3]:
X_broad = X_TFactivities_broad.pivot(values="TF activity score", index="sample", columns=["gene"])
X_broad.head()

gene,AR,FOS,FOSL1,FOXO1,GATA2,IRF1,MYC,NFATC1,NFKB1,RELA,SOX2,SPI1,STAT1,STAT2,STAT3,STAT4,STAT6,TBX21
sample,,,,,,,,,,,,,,,,,,
SIDM00001,-3.541276,-0.330966,-0.423200,0.510541,0.107477,5.030097,-0.172900,1.333479,4.302539,3.084642,-0.911085,6.194435,2.809228,0.847982,-1.112059,2.089240,0.332944,3.859296
SIDM00005,-3.987647,-2.830855,0.704617,-1.931544,-1.384505,-1.542503,-6.123899,-1.115811,-2.922073,-3.595709,-0.818795,-2.255999,-2.875264,-1.392960,-2.582800,-0.725619,-0.008506,-0.873064
SIDM00008,-1.883773,2.343044,0.698489,0.518416,1.954996,0.978567,-6.534764,1.242436,4.513697,3.999274,2.783495,1.632235,-1.995232,1.948572,1.731846,1.712673,1.346131,1.031253
SIDM00011,-1.058458,1.624131,-0.786086,-0.078463,3.160723,-0.085951,-6.797443,4.076593,-0.185916,-0.127614,0.327426,2.338943,-0.450481,0.236227,-1.039279,0.925985,1.163530,1.095876
SIDM00015,-2.535377,-0.314842,0.275515,-0.240138,-0.871939,1.406169,-7.473478,-1.418844,0.882683,0.498863,0.269346,-1.055084,-0.067370,2.081881,-0.162005,0.091977,2.924677,-0.347223

The target y needs to be a binary series. We pick one threshold, in this case the 0.5 quantile (a.k.a. the median).

In [4]:
q = 0.5

y_series = y_PDL1expression_broad.set_index("sample")["PDL1 expression"]
y_broad = (y_series >= y_series.quantile(q))

y_broad

sample
SIDM00001     True
SIDM00005    False
SIDM00008     True
SIDM00011     True
SIDM00015     True
             ...
SIDM01782     True
SIDM01820    False
SIDM01858    False
SIDM01859    False
SIDM01873    False
Name: PDL1 expression, Length: 849, dtype: bool

# Greedy mode

Below we illustrate the greedy method.
The following parameters need to be given:
- X (DataFrame): the (continuous) input data X
- y (Series): the binary target data
- C (int): the maximum number of iterations / rules
- D (int): the maximum number of TF per rule (in this example, D=3 is already slow)
- n_quantiles (optional int, default 9): number of thresholds to consider per TF
- beta (optional non-negative float, default 0): margin width. When set to greater than 0, the ramp loss model is used with this margin loss
- verbose (optional boolean, default True): whether to print elaborate logs during solving

There are a number of advanced features outlined in the docstring.
Note that X and y need to have a matching index (i.e. sample ID)

It returns the ruleset (list of list of Clauses) and a DataFrame with information about each round, i.e. the accuracy after iteration x.

In [5]:
from scripts.py.greedy import solve_greedy

ruleset, records = solve_greedy(X_broad, y_broad, C=3, D=2, verbose=False)

ruleset

162567it [00:07, 21809.42it/s]

['FOS>=-1.258489889098762', 'STAT2>=-0.199141937494325']

162567it [00:06, 26401.87it/s]

['FOSL1>=0.192124456300126', 'STAT2>=-0.7008762082965488']

162567it [00:05, 27986.95it/s]

['RELA>=-2.9256522978246777', '-TBX21>=0.7922907559387328']
~ Finished.
Final objective: 528.0
Final accuracy: 0.7361601884570083

[[FOS >= -1.258 Q(0.200), STAT2 >= -0.199 Q(0.500)],
 [FOSL1 >= 0.192 Q(0.799), STAT2 >= -0.701 Q(0.601)],
 [RELA >= -2.926 Q(0.101), TBX21 <= -0.792 Q(0.101)]]

In [6]:
records.head()

,it,num_total,num_pos,num_neg,rule,num_caught,num_pos_classified,frac_of_total,num_pos_left,accuracy
0,0,849,425,424,"[FOS >= -1.258 Q(0.200), STAT2 >= -0.199 Q(0.5...",0,398,0.468787,138,0.706714
1,1,451,138,313,"[FOSL1 >= 0.192 Q(0.799), STAT2 >= -0.701 Q(0....",0,37,0.043581,112,0.724382
2,2,414,112,302,"[RELA >= -2.926 Q(0.101), TBX21 <= -0.792 Q(0....",0,26,0.030624,94,0.736160

In verbose mode, useful information is printed during solving.

Usually, however, it is preferred to perform performance analysis on the result separately.
To evaluate the result on a dataset (which may also be, for instance, a test dataset), we may do the following:

In [7]:
from scripts.py.model import classify_ruleset
from sklearn.metrics import accuracy_score, precision_score, recall_score

y_hat = classify_ruleset(X_broad, ruleset) # predicted target

print("Train accuracy:", accuracy_score(y_broad, y_hat))
print("Train precision:", precision_score(y_broad, y_hat))
print("Train recall:", recall_score(y_broad, y_hat))

Train accuracy: 0.7361601884570083
Train precision: 0.7180043383947939
Train recall: 0.7788235294117647

# Advanced mode

We now illustrate how to use the advanced C++ solver.

To use the advanced solver, an executable is needed. The executable needed depends on the operating system.
* **Windows**: unpack `release-windows.zip`. Make sure all the DLL files are in the `release-windows/` folder and that `rs.exe` is in that same folder.
* **Linux**: we assume the `rs` executable is available in the `build/` folder after following the Build Instructions in `README.md`.

Below is how to use the advanced solver once the executable is in place. This example was written on a Linux machine. To use it on windows, simply add the parameter `executable='release-windows/rs.exe'`, as illustrated in the commented line.

In [12]:
import importlib
import scripts.py.advanced
importlib.reload(scripts.py.advanced)
from scripts.py.advanced import solve_advanced

ruleset, solve_info = solve_advanced(X_broad, y_broad, 3, 3, n_quantiles=9, exact_enabled=False, timelimit=20)
# For Windows users:
# ruleset, solve_info = solve_advanced(X_broad, y_broad, 3, 3, n_quantiles=9, exact_enabled=False, timelimit=20, executable='release-windows/rs.exe')

Using settings passed as parameters
Program name: build/rs
'X' file: temp/495d4633-4352-4c2c-8a9b-970acdc1ba09_X.csv
'y' file: temp/495d4633-4352-4c2c-8a9b-970acdc1ba09_y.csv
'C': 3
Output file: temp/495d4633-4352-4c2c-8a9b-970acdc1ba09_O.json
Settings file: temp/495d4633-4352-4c2c-8a9b-970acdc1ba09_S.set
'b': 0.0
Reading parameters from <temp/495d4633-4352-4c2c-8a9b-970acdc1ba09_S.set>.

Changed settings:
limits/time = 20
rs/rule_complexity_type = 0
rs/exact/enabled = FALSE
rs/heuristic/beam_widths = "1000,1000,1000"
rs/heuristic/diversity = 1
rs/exact/D = 3
rs/threshold/nonadditive = TRUE

Quantile levels: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
Clause 0: (0>=-3.48984)
Clause 1: (0>=-2.95649)
Clause 2: (0>=-2.56725)
Clause 3: (0>=-2.18629)
Clause 4: (0>=-1.83957)
Clause 5: (0>=-1.39504)
Clause 6: (0>=-0.960511)
Clause 7: (0>=-0.249344)
Clause 8: (0>=0.777586)
Clause 9: (1>=-1.85254)
Clause 10: (1>=-1.25849)
Clause 11: (1>=-0.784411)
Clause 12: (1>=-0.341346)
Clause 13: (1>=0.00569306)
Clause 14: (1>=0.503456)
Clause 15: (1>=1.05233)
Clause 16: (1>=1.69514)
Clause 17: (1>=2.80894)
Clause 18: (2>=-0.702489)
Clause 19: (2>=-0.472786)
Clause 20: (2>=-0.336815)
Clause 21: (2>=-0.181443)
Clause 22: (2>=-0.0403578)
Clause 23: (2>=0.134828)
Clause 24: (2>=0.413463)
Clause 25: (2>=0.772306)
Clause 26: (2>=1.3828)
Clause 27: (3>=-1.35313)
Clause 28: (3>=-1.0285)
Clause 29: (3>=-0.723731)
Clause 30: (3>=-0.47968)
Clause 31: (3>=-0.244486)
Clause 32: (3>=0.0326719)
Clause 33: (3>=0.384321)
Clause 34: (3>=0.817797)
Clause 35: (3>=1.34465)
Clause 36: (4>=-0.805022)
Clause 37: (4>=-0.444751)
Clause 38: (4>=-0.187277)
Clause 39: (4>=0.0627625)
Clause 40: (4>=0.30593)
Clause 41: (4>=0.613126)
Clause 42: (4>=0.92311)
Clause 43: (4>=1.2909)
Clause 44: (4>=1.91675)
Clause 45: (5>=-1.5895)
Clause 46: (5>=-1.10562)
Clause 47: (5>=-0.688853)
Clause 48: (5>=-0.334028)
Clause 49: (5>=0.00705595)
Clause 50: (5>=0.387056)
Clause 51: (5>=0.867466)
Clause 52: (5>=1.46049)
Clause 53: (5>=2.38759)
Clause 54: (6>=-8.79538)
Clause 55: (6>=-7.51014)
Clause 56: (6>=-6.61222)
Clause 57: (6>=-5.62051)
Clause 58: (6>=-4.80783)
Clause 59: (6>=-4.02609)
Clause 60: (6>=-3.19818)
Clause 61: (6>=-1.93755)
Clause 62: (6>=-0.41147)
Clause 63: (7>=-1.06838)
Clause 64: (7>=-0.672344)
Clause 65: (7>=-0.404131)
Clause 66: (7>=-0.132302)
Clause 67: (7>=0.126178)
Clause 68: (7>=0.422603)
Clause 69: (7>=0.809586)
Clause 70: (7>=1.27532)
Clause 71: (7>=2.18194)
Clause 72: (8>=-2.06395)
Clause 73: (8>=-1.16505)
Clause 74: (8>=-0.586936)
Clause 75: (8>=-0.0263843)
Clause 76: (8>=0.347475)
Clause 77: (8>=0.880876)
Clause 78: (8>=1.58857)
Clause 79: (8>=2.3614)
Clause 80: (8>=3.40077)
Clause 81: (9>=-2.45376)
Clause 82: (9>=-1.60186)
Clause 83: (9>=-1.07177)
Clause 84: (9>=-0.475893)
Clause 85: (9>=0.0280417)
Clause 86: (9>=0.598067)
Clause 87: (9>=1.2751)
Clause 88: (9>=2.21834)
Clause 89: (9>=3.31476)
Clause 90: (10>=-0.785595)
Clause 91: (10>=-0.41922)
Clause 92: (10>=-0.143594)
Clause 93: (10>=0.193476)
Clause 94: (10>=0.447665)
Clause 95: (10>=0.793991)
Clause 96: (10>=1.0714)
Clause 97: (10>=1.42922)
Clause 98: (10>=1.94837)
Clause 99: (11>=-1.76906)
Clause 100: (11>=-1.13448)
Clause 101: (11>=-0.59112)
Clause 102: (11>=-0.193164)
Clause 103: (11>=0.360471)
Clause 104: (11>=0.906507)
Clause 105: (11>=1.37735)
Clause 106: (11>=2.20467)
Clause 107: (11>=3.47327)
Clause 108: (12>=-3.04161)
Clause 109: (12>=-2.53712)
Clause 110: (12>=-1.99427)
Clause 111: (12>=-1.61808)
Clause 112: (12>=-1.17905)
Clause 113: (12>=-0.791659)
Clause 114: (12>=-0.257192)
Clause 115: (12>=0.437248)
Clause 116: (12>=1.32465)
Clause 117: (13>=-1.24024)
Clause 118: (13>=-0.951094)
Clause 119: (13>=-0.743469)
Clause 120: (13>=-0.506461)
Clause 121: (13>=-0.199142)
Clause 122: (13>=0.127948)
Clause 123: (13>=0.576987)
Clause 124: (13>=1.05239)
Clause 125: (13>=1.9453)
Clause 126: (14>=-1.88893)
Clause 127: (14>=-1.37672)
Clause 128: (14>=-0.942735)
Clause 129: (14>=-0.542146)
Clause 130: (14>=-0.165537)
Clause 131: (14>=0.354341)
Clause 132: (14>=0.84013)
Clause 133: (14>=1.52625)
Clause 134: (14>=2.52406)
Clause 135: (15>=-0.422606)
Clause 136: (15>=-0.152415)
Clause 137: (15>=0.0703153)
Clause 138: (15>=0.251155)
Clause 139: (15>=0.453732)
Clause 140: (15>=0.650316)
Clause 141: (15>=0.867847)
Clause 142: (15>=1.19119)
Clause 143: (15>=1.61598)
Clause 144: (16>=-0.810043)
Clause 145: (16>=-0.362395)
Clause 146: (16>=-0.0221931)
Clause 147: (16>=0.270353)
Clause 148: (16>=0.592324)
Clause 149: (16>=0.937764)
Clause 150: (16>=1.34508)
Clause 151: (16>=1.83973)
Clause 152: (16>=2.70885)
Clause 153: (17>=-0.712487)
Clause 154: (17>=-0.464559)
Clause 155: (17>=-0.303301)
Clause 156: (17>=-0.156812)
Clause 157: (17>=-0.0258572)
Clause 158: (17>=0.136274)
Clause 159: (17>=0.383435)
Clause 160: (17>=0.706563)
Clause 161: (17>=1.21806)
Clause 162: (18>=-0.777586)
Clause 163: (18>=0.249344)
Clause 164: (18>=0.960511)
Clause 165: (18>=1.39504)
Clause 166: (18>=1.83957)
Clause 167: (18>=2.18629)
Clause 168: (18>=2.56725)
Clause 169: (18>=2.95649)
Clause 170: (18>=3.48984)
Clause 171: (19>=-2.80894)
Clause 172: (19>=-1.69514)
Clause 173: (19>=-1.05233)
Clause 174: (19>=-0.503456)
Clause 175: (19>=-0.00569306)
Clause 176: (19>=0.341346)
Clause 177: (19>=0.784411)
Clause 178: (19>=1.25849)
Clause 179: (19>=1.85254)
Clause 180: (20>=-1.3828)
Clause 181: (20>=-0.772306)
Clause 182: (20>=-0.413463)
Clause 183: (20>=-0.134828)
Clause 184: (20>=0.0403578)
Clause 185: (20>=0.181443)
Clause 186: (20>=0.336815)
Clause 187: (20>=0.472786)
Clause 188: (20>=0.702489)
Clause 189: (21>=-1.34465)
Clause 190: (21>=-0.817797)
Clause 191: (21>=-0.384321)
Clause 192: (21>=-0.0326719)
Clause 193: (21>=0.244486)
Clause 194: (21>=0.47968)
Clause 195: (21>=0.723731)
Clause 196: (21>=1.0285)
Clause 197: (21>=1.35313)
Clause 198: (22>=-1.91675)
Clause 199: (22>=-1.2909)
Clause 200: (22>=-0.92311)
Clause 201: (22>=-0.613126)
Clause 202: (22>=-0.30593)
Clause 203: (22>=-0.0627625)
Clause 204: (22>=0.187277)
Clause 205: (22>=0.444751)
Clause 206: (22>=0.805022)
Clause 207: (23>=-2.38759)
Clause 208: (23>=-1.46049)
Clause 209: (23>=-0.867466)
Clause 210: (23>=-0.387056)
Clause 211: (23>=-0.00705595)
Clause 212: (23>=0.334028)
Clause 213: (23>=0.688853)
Clause 214: (23>=1.10562)
Clause 215: (23>=1.5895)
Clause 216: (24>=0.41147)
Clause 217: (24>=1.93755)
Clause 218: (24>=3.19818)
Clause 219: (24>=4.02609)
Clause 220: (24>=4.80783)
Clause 221: (24>=5.62051)
Clause 222: (24>=6.61222)
Clause 223: (24>=7.51014)
Clause 224: (24>=8.79538)
Clause 225: (25>=-2.18194)
Clause 226: (25>=-1.27532)
Clause 227: (25>=-0.809586)
Clause 228: (25>=-0.422603)
Clause 229: (25>=-0.126178)
Clause 230: (25>=0.132302)
Clause 231: (25>=0.404131)
Clause 232: (25>=0.672344)
Clause 233: (25>=1.06838)
Clause 234: (26>=-3.40077)
Clause 235: (26>=-2.3614)
Clause 236: (26>=-1.58857)
Clause 237: (26>=-0.880876)
Clause 238: (26>=-0.347475)
Clause 239: (26>=0.0263843)
Clause 240: (26>=0.586936)
Clause 241: (26>=1.16505)
Clause 242: (26>=2.06395)
Clause 243: (27>=-3.31476)
Clause 244: (27>=-2.21834)
Clause 245: (27>=-1.2751)
Clause 246: (27>=-0.598067)
Clause 247: (27>=-0.0280417)
Clause 248: (27>=0.475893)
Clause 249: (27>=1.07177)
Clause 250: (27>=1.60186)
Clause 251: (27>=2.45376)
Clause 252: (28>=-1.94837)
Clause 253: (28>=-1.42922)
Clause 254: (28>=-1.0714)
Clause 255: (28>=-0.793991)
Clause 256: (28>=-0.447665)
Clause 257: (28>=-0.193476)
Clause 258: (28>=0.143594)
Clause 259: (28>=0.41922)
Clause 260: (28>=0.785595)
Clause 261: (29>=-3.47327)
Clause 262: (29>=-2.20467)
Clause 263: (29>=-1.37735)
Clause 264: (29>=-0.906507)
Clause 265: (29>=-0.360471)
Clause 266: (29>=0.193164)
Clause 267: (29>=0.59112)
Clause 268: (29>=1.13448)
Clause 269: (29>=1.76906)
Clause 270: (30>=-1.32465)
Clause 271: (30>=-0.437248)
Clause 272: (30>=0.257192)
Clause 273: (30>=0.791659)
Clause 274: (30>=1.17905)
Clause 275: (30>=1.61808)
Clause 276: (30>=1.99427)
Clause 277: (30>=2.53712)
Clause 278: (30>=3.04161)
Clause 279: (31>=-1.9453)
Clause 280: (31>=-1.05239)
Clause 281: (31>=-0.576987)
Clause 282: (31>=-0.127948)
Clause 283: (31>=0.199142)
Clause 284: (31>=0.506461)
Clause 285: (31>=0.743469)
Clause 286: (31>=0.951094)
Clause 287: (31>=1.24024)
Clause 288: (32>=-2.52406)
Clause 289: (32>=-1.52625)
Clause 290: (32>=-0.84013)
Clause 291: (32>=-0.354341)
Clause 292: (32>=0.165537)
Clause 293: (32>=0.542146)
Clause 294: (32>=0.942735)
Clause 295: (32>=1.37672)
Clause 296: (32>=1.88893)
Clause 297: (33>=-1.61598)
Clause 298: (33>=-1.19119)
Clause 299: (33>=-0.867847)
Clause 300: (33>=-0.650316)
Clause 301: (33>=-0.453732)
Clause 302: (33>=-0.251155)
Clause 303: (33>=-0.0703153)
Clause 304: (33>=0.152415)
Clause 305: (33>=0.422606)
Clause 306: (34>=-2.70885)
Clause 307: (34>=-1.83973)
Clause 308: (34>=-1.34508)
Clause 309: (34>=-0.937764)
Clause 310: (34>=-0.592324)
Clause 311: (34>=-0.270353)
Clause 312: (34>=0.0221931)
Clause 313: (34>=0.362395)
Clause 314: (34>=0.810043)
Clause 315: (35>=-1.21806)
Clause 316: (35>=-0.706563)
Clause 317: (35>=-0.383435)
Clause 318: (35>=-0.136274)
Clause 319: (35>=0.0258572)
Clause 320: (35>=0.156812)
Clause 321: (35>=0.303301)
Clause 322: (35>=0.464559)
Clause 323: (35>=0.712487)
Starting solve. Method: Price then branch.
Starting pricing phase.
Quantile levels: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
Clause 0: (0>=-3.48984)
Clause 1: (0>=-2.95649)
Clause 2: (0>=-2.56725)
Clause 3: (0>=-2.18629)
Clause 4: (0>=-1.83957)
Clause 5: (0>=-1.39504)
Clause 6: (0>=-0.960511)
Clause 7: (0>=-0.249344)
Clause 8: (0>=0.777586)
Clause 9: (1>=-1.85254)
Clause 10: (1>=-1.25849)
Clause 11: (1>=-0.784411)
Clause 12: (1>=-0.341346)
Clause 13: (1>=0.00569306)
Clause 14: (1>=0.503456)
Clause 15: (1>=1.05233)
Clause 16: (1>=1.69514)
Clause 17: (1>=2.80894)
Clause 18: (2>=-0.702489)
Clause 19: (2>=-0.472786)
Clause 20: (2>=-0.336815)
Clause 21: (2>=-0.181443)
Clause 22: (2>=-0.0403578)
Clause 23: (2>=0.134828)
Clause 24: (2>=0.413463)
Clause 25: (2>=0.772306)
Clause 26: (2>=1.3828)
Clause 27: (3>=-1.35313)
Clause 28: (3>=-1.0285)
Clause 29: (3>=-0.723731)
Clause 30: (3>=-0.47968)
Clause 31: (3>=-0.244486)
Clause 32: (3>=0.0326719)
Clause 33: (3>=0.384321)
Clause 34: (3>=0.817797)
Clause 35: (3>=1.34465)
Clause 36: (4>=-0.805022)
Clause 37: (4>=-0.444751)
Clause 38: (4>=-0.187277)
Clause 39: (4>=0.0627625)
Clause 40: (4>=0.30593)
Clause 41: (4>=0.613126)
Clause 42: (4>=0.92311)
Clause 43: (4>=1.2909)
Clause 44: (4>=1.91675)
Clause 45: (5>=-1.5895)
Clause 46: (5>=-1.10562)
Clause 47: (5>=-0.688853)
Clause 48: (5>=-0.334028)
Clause 49: (5>=0.00705595)
Clause 50: (5>=0.387056)
Clause 51: (5>=0.867466)
Clause 52: (5>=1.46049)
Clause 53: (5>=2.38759)
Clause 54: (6>=-8.79538)
Clause 55: (6>=-7.51014)
Clause 56: (6>=-6.61222)
Clause 57: (6>=-5.62051)
Clause 58: (6>=-4.80783)
Clause 59: (6>=-4.02609)
Clause 60: (6>=-3.19818)
Clause 61: (6>=-1.93755)
Clause 62: (6>=-0.41147)
Clause 63: (7>=-1.06838)
Clause 64: (7>=-0.672344)
Clause 65: (7>=-0.404131)
Clause 66: (7>=-0.132302)
Clause 67: (7>=0.126178)
Clause 68: (7>=0.422603)
Clause 69: (7>=0.809586)
Clause 70: (7>=1.27532)
Clause 71: (7>=2.18194)
Clause 72: (8>=-2.06395)
Clause 73: (8>=-1.16505)
Clause 74: (8>=-0.586936)
Clause 75: (8>=-0.0263843)
Clause 76: (8>=0.347475)
Clause 77: (8>=0.880876)
Clause 78: (8>=1.58857)
Clause 79: (8>=2.3614)
Clause 80: (8>=3.40077)
Clause 81: (9>=-2.45376)
Clause 82: (9>=-1.60186)
Clause 83: (9>=-1.07177)
Clause 84: (9>=-0.475893)
Clause 85: (9>=0.0280417)
Clause 86: (9>=0.598067)
Clause 87: (9>=1.2751)
Clause 88: (9>=2.21834)
Clause 89: (9>=3.31476)
Clause 90: (10>=-0.785595)
Clause 91: (10>=-0.41922)
Clause 92: (10>=-0.143594)
Clause 93: (10>=0.193476)
Clause 94: (10>=0.447665)
Clause 95: (10>=0.793991)
Clause 96: (10>=1.0714)
Clause 97: (10>=1.42922)
Clause 98: (10>=1.94837)
Clause 99: (11>=-1.76906)
Clause 100: (11>=-1.13448)
Clause 101: (11>=-0.59112)
Clause 102: (11>=-0.193164)
Clause 103: (11>=0.360471)
Clause 104: (11>=0.906507)
Clause 105: (11>=1.37735)
Clause 106: (11>=2.20467)
Clause 107: (11>=3.47327)
Clause 108: (12>=-3.04161)
Clause 109: (12>=-2.53712)
Clause 110: (12>=-1.99427)
Clause 111: (12>=-1.61808)
Clause 112: (12>=-1.17905)
Clause 113: (12>=-0.791659)
Clause 114: (12>=-0.257192)
Clause 115: (12>=0.437248)
Clause 116: (12>=1.32465)
Clause 117: (13>=-1.24024)
Clause 118: (13>=-0.951094)
Clause 119: (13>=-0.743469)
Clause 120: (13>=-0.506461)
Clause 121: (13>=-0.199142)
Clause 122: (13>=0.127948)
Clause 123: (13>=0.576987)
Clause 124: (13>=1.05239)
Clause 125: (13>=1.9453)
Clause 126: (14>=-1.88893)
Clause 127: (14>=-1.37672)
Clause 128: (14>=-0.942735)
Clause 129: (14>=-0.542146)
Clause 130: (14>=-0.165537)
Clause 131: (14>=0.354341)
Clause 132: (14>=0.84013)
Clause 133: (14>=1.52625)
Clause 134: (14>=2.52406)
Clause 135: (15>=-0.422606)
Clause 136: (15>=-0.152415)
Clause 137: (15>=0.0703153)
Clause 138: (15>=0.251155)
Clause 139: (15>=0.453732)
Clause 140: (15>=0.650316)
Clause 141: (15>=0.867847)
Clause 142: (15>=1.19119)
Clause 143: (15>=1.61598)
Clause 144: (16>=-0.810043)
Clause 145: (16>=-0.362395)
Clause 146: (16>=-0.0221931)
Clause 147: (16>=0.270353)
Clause 148: (16>=0.592324)
Clause 149: (16>=0.937764)
Clause 150: (16>=1.34508)
Clause 151: (16>=1.83973)
Clause 152: (16>=2.70885)
Clause 153: (17>=-0.712487)
Clause 154: (17>=-0.464559)
Clause 155: (17>=-0.303301)
Clause 156: (17>=-0.156812)
Clause 157: (17>=-0.0258572)
Clause 158: (17>=0.136274)
Clause 159: (17>=0.383435)
Clause 160: (17>=0.706563)
Clause 161: (17>=1.21806)
Clause 162: (18>=-0.777586)
Clause 163: (18>=0.249344)
Clause 164: (18>=0.960511)
Clause 165: (18>=1.39504)
Clause 166: (18>=1.83957)
Clause 167: (18>=2.18629)
Clause 168: (18>=2.56725)
Clause 169: (18>=2.95649)
Clause 170: (18>=3.48984)
Clause 171: (19>=-2.80894)
Clause 172: (19>=-1.69514)
Clause 173: (19>=-1.05233)
Clause 174: (19>=-0.503456)
Clause 175: (19>=-0.00569306)
Clause 176: (19>=0.341346)
Clause 177: (19>=0.784411)
Clause 178: (19>=1.25849)
Clause 179: (19>=1.85254)
Clause 180: (20>=-1.3828)
Clause 181: (20>=-0.772306)
Clause 182: (20>=-0.413463)
Clause 183: (20>=-0.134828)
Clause 184: (20>=0.0403578)
Clause 185: (20>=0.181443)
Clause 186: (20>=0.336815)
Clause 187: (20>=0.472786)
Clause 188: (20>=0.702489)
Clause 189: (21>=-1.34465)
Clause 190: (21>=-0.817797)
Clause 191: (21>=-0.384321)
Clause 192: (21>=-0.0326719)
Clause 193: (21>=0.244486)
Clause 194: (21>=0.47968)
Clause 195: (21>=0.723731)
Clause 196: (21>=1.0285)
Clause 197: (21>=1.35313)
Clause 198: (22>=-1.91675)
Clause 199: (22>=-1.2909)
Clause 200: (22>=-0.92311)
Clause 201: (22>=-0.613126)
Clause 202: (22>=-0.30593)
Clause 203: (22>=-0.0627625)
Clause 204: (22>=0.187277)
Clause 205: (22>=0.444751)
Clause 206: (22>=0.805022)
Clause 207: (23>=-2.38759)
Clause 208: (23>=-1.46049)
Clause 209: (23>=-0.867466)
Clause 210: (23>=-0.387056)
Clause 211: (23>=-0.00705595)
Clause 212: (23>=0.334028)
Clause 213: (23>=0.688853)
Clause 214: (23>=1.10562)
Clause 215: (23>=1.5895)
Clause 216: (24>=0.41147)
Clause 217: (24>=1.93755)
Clause 218: (24>=3.19818)
Clause 219: (24>=4.02609)
Clause 220: (24>=4.80783)
Clause 221: (24>=5.62051)
Clause 222: (24>=6.61222)
Clause 223: (24>=7.51014)
Clause 224: (24>=8.79538)
Clause 225: (25>=-2.18194)
Clause 226: (25>=-1.27532)
Clause 227: (25>=-0.809586)
Clause 228: (25>=-0.422603)
Clause 229: (25>=-0.126178)
Clause 230: (25>=0.132302)
Clause 231: (25>=0.404131)
Clause 232: (25>=0.672344)
Clause 233: (25>=1.06838)
Clause 234: (26>=-3.40077)
Clause 235: (26>=-2.3614)
Clause 236: (26>=-1.58857)
Clause 237: (26>=-0.880876)
Clause 238: (26>=-0.347475)
Clause 239: (26>=0.0263843)
Clause 240: (26>=0.586936)
Clause 241: (26>=1.16505)
Clause 242: (26>=2.06395)
Clause 243: (27>=-3.31476)
Clause 244: (27>=-2.21834)
Clause 245: (27>=-1.2751)
Clause 246: (27>=-0.598067)
Clause 247: (27>=-0.0280417)
Clause 248: (27>=0.475893)
Clause 249: (27>=1.07177)
Clause 250: (27>=1.60186)
Clause 251: (27>=2.45376)
Clause 252: (28>=-1.94837)
Clause 253: (28>=-1.42922)
Clause 254: (28>=-1.0714)
Clause 255: (28>=-0.793991)
Clause 256: (28>=-0.447665)
Clause 257: (28>=-0.193476)
Clause 258: (28>=0.143594)
Clause 259: (28>=0.41922)
Clause 260: (28>=0.785595)
Clause 261: (29>=-3.47327)
Clause 262: (29>=-2.20467)
Clause 263: (29>=-1.37735)
Clause 264: (29>=-0.906507)
Clause 265: (29>=-0.360471)
Clause 266: (29>=0.193164)
Clause 267: (29>=0.59112)
Clause 268: (29>=1.13448)
Clause 269: (29>=1.76906)
Clause 270: (30>=-1.32465)
Clause 271: (30>=-0.437248)
Clause 272: (30>=0.257192)
Clause 273: (30>=0.791659)
Clause 274: (30>=1.17905)
Clause 275: (30>=1.61808)
Clause 276: (30>=1.99427)
Clause 277: (30>=2.53712)
Clause 278: (30>=3.04161)
Clause 279: (31>=-1.9453)
Clause 280: (31>=-1.05239)
Clause 281: (31>=-0.576987)
Clause 282: (31>=-0.127948)
Clause 283: (31>=0.199142)
Clause 284: (31>=0.506461)
Clause 285: (31>=0.743469)
Clause 286: (31>=0.951094)
Clause 287: (31>=1.24024)
Clause 288: (32>=-2.52406)
Clause 289: (32>=-1.52625)
Clause 290: (32>=-0.84013)
Clause 291: (32>=-0.354341)
Clause 292: (32>=0.165537)
Clause 293: (32>=0.542146)
Clause 294: (32>=0.942735)
Clause 295: (32>=1.37672)
Clause 296: (32>=1.88893)
Clause 297: (33>=-1.61598)
Clause 298: (33>=-1.19119)
Clause 299: (33>=-0.867847)
Clause 300: (33>=-0.650316)
Clause 301: (33>=-0.453732)
Clause 302: (33>=-0.251155)
Clause 303: (33>=-0.0703153)
Clause 304: (33>=0.152415)
Clause 305: (33>=0.422606)
Clause 306: (34>=-2.70885)
Clause 307: (34>=-1.83973)
Clause 308: (34>=-1.34508)
Clause 309: (34>=-0.937764)
Clause 310: (34>=-0.592324)
Clause 311: (34>=-0.270353)
Clause 312: (34>=0.0221931)
Clause 313: (34>=0.362395)
Clause 314: (34>=0.810043)
Clause 315: (35>=-1.21806)
Clause 316: (35>=-0.706563)
Clause 317: (35>=-0.383435)
Clause 318: (35>=-0.136274)
Clause 319: (35>=0.0258572)
Clause 320: (35>=0.156812)
Clause 321: (35>=0.303301)
Clause 322: (35>=0.464559)
Clause 323: (35>=0.712487)
Heuristic pricer enabled.
feasible solution found by trivial heuristic after 0.0 seconds, objective value 4.250000e+07
presolving:
presolving (0 rounds: 0 fast, 0 medium, 0 exhaustive):
 0 deleted vars, 0 deleted constraints, 0 added constraints, 0 tightened bounds, 0 added holes, 0 changed sides, 0 changed coefficients
 0 implications, 0 cliques, 0 implied integral variables (0 bin, 0 int, 0 cont)
presolved problem has 425 variables (0 bin, 0 int, 425 cont) and 426 constraints
    426 constraints of type <linear>
Presolving Time: 0.00
transformed 1/1 original solutions to the transformed problem space

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl.
* 0.0s|     1 |     0 |   425 |     - |    LP  |   0 | 425 | 426 | 426 |   0 |  0 |   0 |   0 |      --      | 8.500000e+02 |    Inf | unknown
Heuristic Pricer Called. Current LP objective: 850 Lambda 0
+ Rule: { (1>=-1.25849) (5>=-1.5895) (13>=-0.199142) }	 Reduced cost: -360
+ Rule: { (5>=-1.5895) (9>=-1.07177) (13>=-0.506461) }	 Reduced cost: -356
+ Rule: { (9>=-1.07177) (13>=-0.506461) (16>=-0.810043) }	 Reduced cost: -354
+ Rule: { (8>=-2.06395) (9>=-1.07177) (13>=-0.506461) }	 Reduced cost: -350
+ Rule: { (7>=-1.06838) (9>=-0.475893) (13>=-0.506461) }	 Reduced cost: -344
+ Rule: { (2>=-0.181443) (13>=-0.199142) (16>=-0.810043) }	 Reduced cost: -342
+ Rule: { (10>=-0.41922) (13>=-0.199142) (16>=-0.810043) }	 Reduced cost: -340
+ Rule: { (4>=-0.805022) (9>=0.0280417) (13>=-0.506461) }	 Reduced cost: -340
+ Rule: { (13>=-0.199142) (14>=-1.37672) (16>=-0.810043) }	 Reduced cost: -334
+ Rule: { (12>=-2.53712) (13>=-0.199142) }	 Reduced cost: -332
  1.6s|     1 |     0 |   654 |     - |  3846k |   0 | 435 | 426 | 426 |   0 |  0 |   0 |   0 |      --      | 8.500000e+02 |    Inf | unknown
Heuristic Pricer Called. Current LP objective: 490 Lambda 0
+ Rule: { (9>=0.0280417) (22>=-1.2909) (24>=1.93755) }	 Reduced cost: -78
+ Rule: { (1>=-0.784411) (9>=0.0280417) (22>=-1.2909) }	 Reduced cost: -70

In [13]:
ruleset

[[FOS >= -0.784 Q(0.300), FOSL1 >= 0.135 Q(0.600), STAT2 >= -0.743 Q(0.300)],
 [RELA >= -2.454 Q(0.100), MYC <= -3.198 Q(0.700), TBX21 <= -0.465 Q(0.200)],
 [STAT1 >= -0.257 Q(0.700), GATA2 <= 0.923 Q(0.700), MYC <= -1.938 Q(0.800)]]

Evaluation of the ruleset works in the same way as before

In [15]:
y_hat = classify_ruleset(X_broad, ruleset) # predicted target
print(accuracy_score(y_hat, y_broad))

0.7585394581861012

If interested, additional information about the solve is available, but these are not documented here.

In [14]:
solve_info

{'C': 3,
 'binary': [['FOS>=-0.784411', 'FOSL1>=0.134828', 'STAT2>=-0.743469'],
  ['RELA>=-2.453757', '-MYC>=3.198181', '-TBX21>=0.464559'],
  ['STAT1>=-0.257192', '-GATA2>=-0.923110', '-MYC>=1.937553']],
 'dualbound': 418.0,
 'margin_width': 0.0,
 'obj': 418.0,
 'obj_cg': 396.82803045746687,
 'obj_relaxation': 1e+20,
 'pricing_steps': [{'lp_objective': 850.0,
   'pricer': 0,
   'red_cost': -360.0,
   'time': 1.557848},
  {'lp_objective': 490.0, 'pricer': 0, 'red_cost': -78.0, 'time': 2.973827},
  {'lp_objective': 466.0, 'pricer': 0, 'red_cost': -56.0, 'time': 4.383955},
  {'lp_objective': 438.0, 'pricer': 0, 'red_cost': -43.0, 'time': 5.529227},
  {'lp_objective': 415.7142857142857,
   'pricer': 0,
   'red_cost': -22.57142857142857,
   'time': 6.29703},
  {'lp_objective': 409.7987804878049,
   'pricer': 0,
   'red_cost': -23.64634146341467,
   'time': 7.031277},
  {'lp_objective': 402.93023255813955,
   'pricer': 0,
   'red_cost': -16.124031007751938,
   'time': 7.745254},
  {'lp_objective': 401.06883789785337,
   'pricer': 0,
   'red_cost': -13.616580310880764,
   'time': 8.344559},
  {'lp_objective': 399.61115414407436,
   'pricer': 0,
   'red_cost': -8.14252517428349,
   'time': 8.945073},
  {'lp_objective': 397.97222222222223,
   'pricer': 0,
   'red_cost': -7.84722222222222,
   'time': 9.532283},
  {'lp_objective': 397.8646034816248,
   'pricer': 0,
   'red_cost': -7.199226305609265,
   'time': 10.11492},
  {'lp_objective': 397.433962264151,
   'pricer': 0,
   'red_cost': -4.528301886792452,
   'time': 10.697338},
  {'lp_objective': 397.32375099127677,
   'pricer': 0,
   'red_cost': -8.126486915146602,
   'time': 11.318915},
  {'lp_objective': 396.92564785662387,
   'pricer': 0,
   'red_cost': -2.0339065148946567,
   'time': 11.985348},
  {'lp_objective': 396.8475896899583,
   'pricer': 0,
   'red_cost': -1.610660109710592,
   'time': 12.695858},
  {'lp_objective': 396.8355569697934,
   'pricer': 0,
   'red_cost': -0.46430438438984734,
   'time': 13.426093999999999}],
 'quantile_levels': [0.1,
  0.2,
  0.30000000000000004,
  0.4,
  0.5,
  0.6000000000000001,
  0.7000000000000001,
  0.8,
  0.9],
 'relaxation': [['AR>=-3.489841',
   'FOSL1>=0.134828',
   'STAT2>=-0.743469',
   0.31578947368421073],
  ['AR>=-1.839573',
   'FOSL1>=0.413463',
   'STAT2>=-0.743469',
   0.15789473684210523],
  ['FOS>=-1.258490',
   'STAT2>=0.127948',
   '-NFATC1>=-2.181944',
   0.13157894736842113],
  ['FOSL1>=-0.181443',
   'STAT2>=-0.199142',
   'STAT6>=0.270353',
   0.05263157894736814],
  ['FOSL1>=0.134828',
   'STAT2>=-0.743469',
   '-GATA2>=-1.290900',
   0.07894736842105275],
  ['FOXO1>=-0.723731',
   'STAT2>=0.127948',
   'STAT6>=0.270353',
   0.15789473684210548],
  ['GATA2>=-0.805022',
   'IRF1>=0.867466',
   'STAT2>=0.576987',
   0.07894736842105264],
  ['GATA2>=0.062763',
   'RELA>=0.028042',
   '-FOXO1>=-0.032672',
   0.026315789473684292],
  ['IRF1>=0.387056',
   'STAT2>=0.576987',
   'STAT6>=-0.362395',
   0.07894736842105265],
  ['NFATC1>=0.126178',
   'RELA>=0.028042',
   '-GATA2>=-0.923110',
   0.23684210526315805],
  ['NFKB1>=-0.026384',
   'STAT2>=-0.199142',
   '-TBX21>=-0.136274',
   0.10526315789473692],
  ['NFKB1>=-0.026384',
   'STAT2>=1.052395',
   '-SPI1>=-3.473268',
   0.0263157894736842],
  ['RELA>=-2.453757', '-MYC>=3.198181', '-TBX21>=0.464559', 0.868421052631579],
  ['RELA>=0.028042',
   '-FOXO1>=-0.384321',
   '-STAT4>=-0.867847',
   0.28947368421052644],
  ['SOX2>=-0.143594',
   'STAT3>=0.354341',
   '-STAT1>=0.791659',
   0.13157894736842135],
  ['SOX2>=0.447665',
   'STAT3>=0.354341',
   'STAT6>=0.592324',
   0.05263157894736842],
  ['SOX2>=1.071404',
   'STAT2>=-0.199142',
   '-STAT1>=-0.437248',
   0.026315789473684074],
  ['STAT1>=-1.994266',
   'STAT2>=0.576987',
   '-MYC>=4.026091',
   0.07894736842105252],
  ['STAT2>=-0.506461',
   'STAT6>=0.592324',
   '-GATA2>=-0.923110',
   0.0789473684210527],
  ['STAT2>=1.945295', 'STAT6>=-0.362395', 0.026315789473684237]],
 'soltime': 1.264142,
 'soltime_cg': 14.196535,
 'status': 1,
 'status_cg': 1}

Several other parameters are available for `solve_advanced`, described in the function's docstring.

For full control over the advanced solver, a custom settings file may be given, like those found in `data/[experiment]/`